import type { Metadata } from "next";
import "@/styles/style.scss";
import React from "react";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "websocket sample",
  description: "Generated by create next app",
};

export const viewports = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
