import type { Metadata } from "next";
import "@/styles/style.scss";
import React from "react";

export const metadata: Metadata = {
  title: "websocket sample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header>header</header>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
